BitGo/api-ts

- packages/io-ts-express/test/test-server.ts
- packages/io-ts-http/src/httpResponse.ts
- packages/superagent-codec-adapter/src/request.ts
- packages/superagent-codec-adapter/test/request.test.ts
> feat: use HTTP status codes in superagent-codec-adapter

- packages/superagent-codec-adapter/README.md
> feat: add how-to guide for superagent-codec-adapter

- .github/workflows/ci.yml
- upgrade setup-node to v3
- cache npm dependencies between builds
- use npm ci over npm install
> ci: reduce runtime and upgrade GitHub actions

- packages/io-ts-openapi/corpus/test-intersection-flattening.ts
- packages/io-ts-openapi/src/type.ts
This is mostly noticeable with `optionalize`d codecs as they internally
are represented as an `io-ts` intersection of two types, one containing
the required properties, and the other the optional ones. With this
change, the resulting OpenAPI spec won't needlessly generate an `allOf`
for these.
Ticket: BG-46081
> feat: simplify intersections of simple types

- .github/workflows/release.yml
- .lintstagedrc.json
- .releaserc.json
- package-lock.json
- package.json
- packages/express-wrapper/package.json
- packages/io-ts-http/package.json
- packages/openapi-generator/package.json
- packages/response/package.json
- packages/superagent-wrapper/package.json
ci: configure semantic-release
This commit configures semantic-release to publish new versions
when semantically appropriate to npm and create a corresponding
GitHub Release.
This punts management of a changelog to #37.
Closes #36.
> Configure semantic-release

- packages/express-wrapper/src/index.ts
- packages/openapi-generator/package.json
For consistency, since the value of this key is a scalar (`string`)
and not a vector, and for congruence with our convention at BitGo of
handling errors.
Closes #39
> fix!: rename errors to error in 400 responses

- packages/io-ts-http/src/httpResponse.ts
- packages/io-ts-http/src/httpRoute.ts
- packages/superagent-wrapper/src/request.ts
Instead of `never` this should be something like the union of all
responses with `any` or `unknown` body.
Broken:
Fixed:
> fix: inference of `ResponseType<HttpRoute>`

- package-lock.json
- package.json
In CI currently[^1] we see the following logs
```
npm WARN exec The following package was not found and will be installed: multi-semantic-release
```
which means we're not locking our CI pipeline to a specific version
of multi-semantic-release.
This commit installs a specific version of multi-semantic-release
in the root package.json.
> chore: install multi-semantic-release

- package-lock.json
- packages/express-wrapper/package.json
- packages/io-ts-http/package.json
- packages/openapi-generator/package.json
- packages/response/package.json
- packages/superagent-wrapper/package.json
`multi-semantic-release`'s readme says to use `*` as the version field for monorepo packages, but this fails in a strange way. This switches them to `0.0.0-semantically-released` as recommended in a Github issue.
See: https://github.com/dhoulb/multi-semantic-release/issues/102
> Fix local pkg versions

- .github/workflows/release.yml
This file should be respected by `semantic-release` according to their
documentation.
See: https://github.com/semantic-release/semantic-release/blob/8fda7fd423d24e7b425fbee83790f49dd0478e2d/docs/support/FAQ.md#can-i-use-npmrc-options
> fix: put .npmrc at default location for release

- packages/response/src/index.ts
The real motivation for this is to trigger a semantic release of
`@api-ts/response`
> fix: add headers to response table

- package-lock.json
- packages/express-wrapper/src/index.ts
- packages/express-wrapper/src/request.ts
- packages/express-wrapper/test/server.test.ts
- packages/io-ts-http/docs/httpRoute.md
- packages/io-ts-http/package.json
- packages/io-ts-http/src/httpResponse.ts
- packages/io-ts-http/src/httpRoute.ts
- packages/io-ts-http/src/index.ts
- packages/io-ts-http/src/statusCode.ts
- packages/openapi-generator/corpus/test-array-property.ts
- packages/openapi-generator/corpus/test-boolean-literal.ts
- packages/openapi-generator/corpus/test-discriminated-union.ts
- packages/openapi-generator/corpus/test-intersection-flattening.ts
- packages/openapi-generator/corpus/test-multi-route.ts
- packages/openapi-generator/corpus/test-multi-union.ts
- packages/openapi-generator/corpus/test-null-param.ts
- packages/openapi-generator/corpus/test-optional-property.ts
- packages/openapi-generator/corpus/test-record-type.ts
- packages/openapi-generator/corpus/test-single-route-multi-method.ts
- packages/openapi-generator/corpus/test-single-route.ts
- packages/openapi-generator/corpus/test-string-union.ts
- packages/openapi-generator/corpus/test-unknown-property.ts
- packages/openapi-generator/corpus/test-version-tag.ts
- packages/openapi-generator/src/route.ts
- packages/superagent-wrapper/src/request.ts
- packages/superagent-wrapper/test/request.test.ts
This PR does two main things:
1) Remove the `response` library from several places, cleaning up several parts of the codebase
2) Allow the `response` library to still be used for creating http-agnostic service functions
On the second point, I tried a few approaches before ultimately punting on it and just extending the "decode request and encode response" function in `express-wrapper` to handle either raw HTTP status codes or `response` ones.
> change the way `response` is used

- README.md
Instructions followed from this webpage:
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
CLOSES TICKET: BG-43006
> doc: add a readme badge with CI status

- packages/express-wrapper/src/index.ts
- packages/express-wrapper/src/request.ts
- packages/express-wrapper/src/response.ts
Fixes a soundness issue with NumericOrKeyedResponseType when instantiated with the maximally-wide HttpRoute, and is the beginning of allowing for customizing the way responses are encoded and then actually sent to Express.
> feat(express-wrapper): allow custom response encoders

- .github/dependabot.yml
I'm not sure if this will work immediately or if we need to find a setting to enable dependabot for this repository. Time will tell!
I'm basing this into master because dependabot probably looks for configuration only on the default branch.
Closes #35
> chore: configure dependabot to upgrade npm packages

- .envrc
- .gitignore
Requires a fairly recent version of nix (I'm on 2.8.0) and opting in
to the following experimental features:
```
nix-command flakes
```
> chore: use nix flakes with direnv

- .github/workflows/release.yml
When I pulled upstream/master and pushed to my fork's master branch,
the release job ran and failed because I did not have the NPM_TOKEN
configured in my GitHub Actions.
This commit prevents the release workflow from running in GitHub
Actions of forks.
> ci: only run release job in BitGo's GitHub Actions

- packages/express-wrapper/src/index.ts
For existing applications that do large amounts of express
configuration, it is often cleaner to just obtain a router instance and
add it to the existing express stack. This assists with incremental
adoption of api-ts
> Add router-returning function to express-wrapper

- package-lock.json
- packages/io-ts-http/package.json
- packages/superagent-wrapper/package.json
We currently list monocle-ts and newtype-ts as explicit dependencies,
since these two packages are peer dependencies of io-ts-types[^1]
and npm 6 doesn't automatically install peer dependencies (like npm
7 does).
This commit removes the explicit peer dependencies, because when npm 7+
is used the behavior will be the same. Additionally, in npm 6 these
to packages won't be installed but they aren't needed, so there will
be no breaking change.
[^1]: https://github.com/gcanti/io-ts-types/blob/master/package.json#L40-L41
> chore: remove explicit peer dependencies

- packages/express-wrapper/src/request.ts
- packages/express-wrapper/src/response.ts
Although it is not ideal, this at least matched the pattern that express uses.
> feat: make response encoder return an express middleware

- flake.nix
Not sure how this snuck in there, but it is not needed to build anything
> chore: remove go from flake.nix

- packages/superagent-wrapper/src/request.ts
- packages/superagent-wrapper/test/request.test.ts
> fix(superagent): do not throw on non-2xx status

- packages/openapi-generator/src/cli.ts
This commit removes the code to calculate a relative path between the
directory containing the tsconfig.json file and the input file. This
permits a copy of @api-ts/openapi-generator installed in one location
to use files from a project in a different location as inputs without
crashing.
Full bug report below.
What I did
----------
```
$ npx openapi-generator \
--input ../lib/grooble/src/index.ts \
--output api.json \
--tsconfig ../lib/grooble/tsconfig.json \
--name "Grooble"
```
What I Expected to Happen
-------------------------
I expected the openapi-generator to create a file named `api.json`
with the OpenAPI spec described by `../lib/grooble/src/index.ts`.
What Actually Happens
---------------------
```
Error processing project: src/index.ts not in project
```
with a non-zero exit …
> fix(openapi-generator): do not calculate relative paths from input files

- package-lock.json
- packages/superagent-wrapper/package.json
- packages/superagent-wrapper/src/request.ts
`@api-ts/superagent-wrapper` only actually uses a small subset of superagent's functionality. This PR adds the necessary type declarations so that it can be compatible with the widest possible range of superagent versions.
> Structural superagent dependency

- packages/io-ts-http/README.md
Add an example of using `io-ts-http`
TICKET: BG-50225
> docs: update README with an example

- packages/io-ts-http/src/combinators.ts
- packages/io-ts-http/src/utils.ts
Adds a utility type that forces the TS language server to simplify
intersection types (at least as of 4.7.4). This greatly improves
readability of the codec types produced by io-ts-http
Before:
After:
> feat: force simplification of intersection types in io-ts-http

- packages/io-ts-http/src/httpRequest.ts
Helps code readability while keeping the error messages the same.
> chore: improve readability of query/param/header types

- packages/superagent-wrapper/src/request.ts
- packages/superagent-wrapper/test/request.test.ts
Should address #137 
Also it brings in `PathReporter` which has a bug as per #138, but we were calling `JSON.stringify` on the error anyway so it doesn't introduce a regression. Will try to sort that out in a follow-up.
> feat: add decoded response to decodeExpecting errors

- packages/express-wrapper/src/index.ts
- packages/express-wrapper/src/middleware.ts
- packages/express-wrapper/src/request.ts
- packages/express-wrapper/test/middleware.test.ts
- packages/express-wrapper/test/server.test.ts
This adds the capability for middleware to define additional properties that get added on to the decoded request object. This is done with the addition of a new exported helper function named `middlewareFn`. It accepts a function with the signature:
```
(req: express.Request, res: express.Response) => Promise<Output>
```
Notice that it is `async` rather than using Express's `next` convention. Properties of `Output` are merged in with the decoded request.
This change should be backwards compatible with existing use of `express-wrapper`. Middleware functions just go in the pipeline alongside normal express middleware. However, it introduces a middleware array length constraint of 8. This is just how much I wanted to write out for now, it can be expanded or we can try to figure out recursive …
> feat(express-wrapper): allow middleware to add request properties

- packages/express-wrapper/src/request.ts
I also figured out how to actually use a narrow impl type without it
complaining.
> fix: add default param to requestHandler impl

- package-lock.json
- packages/express-wrapper/src/index.ts
- packages/express-wrapper/src/request.ts
- packages/typed-express-router/package.json
- packages/typed-express-router/src/errors.ts
- packages/typed-express-router/src/index.ts
- packages/typed-express-router/src/telemetry.ts
- packages/typed-express-router/src/types.ts
- packages/typed-express-router/test/server.test.ts
- packages/typed-express-router/test/telemetry.test.ts
Ticket: DX-1473
This PR implements `opentelemetry` instrumentation for the `decode` and `sendEncoded` calls in `wrapRouter`. 
Changes:
- `typed-express-wrapper`
- `@opentelemetry/api@^1.0.0` added as an optional peer dependency
- `@opentelemetry/sdk-trace-base@1.30.1` , `@opentelemetry/sdk-trace-node@1.30.1`, and `@opentelemetry/api@1.9.0` added as dev dependencies
- `wrapRouter` modified to create decode and encode spans if `@opentelemetry/api` is installed
- if `@opentelemetry/api` is not installed, spans are not created
- `onDecodeError` option removed. Please use `decodeErrorFormatter` and `getDecodeErrorStatusCode`
- `decodeErrorFormatter` takes in an array of `ValidationError`s and a `WrappedRequest`, returning a `Json` object.
- `getDecodeErrorStatusCode` takes in an array of …
> feat(opentelemetry): create otel instrumentation for typed-express-router

- packages/openapi-generator/src/apiSpec.ts
- packages/openapi-generator/test/identifierApiSpec.test.ts
Add support for passing variables directly to apiSpec() without
requiring object literal syntax with spread operator.
Previously, this would fail:
```typescript
export const MyApiSpec = apiSpec(myApiSpecProps);
```
And required this workaround:
```typescript
export const MyApiSpec = apiSpec({
...myApiSpecProps
});
```
This change resolves identifiers when passed directly to apiSpec(),
handling both nested and imported identifiers.
Closes Ticket: DX-1604
> feat(openapi-generator): support Identifier type in route expressions

- packages/openapi-generator/src/codec.ts
- packages/openapi-generator/test/nestedMemberExpression.test.ts
The test case describes the newly-supported functionality!
Closes Ticket: DX-1608
> feat(openapi-generator): support nested member expression

- packages/openapi-generator/src/openapi.ts
- packages/openapi-generator/test/openapi/ref.test.ts
Fixes the no-$ref-siblings error seen in this [PR](https://github.com/BitGo/dev-portal/pull/2508)
Ticket: DX-1580
This is done by wrapping innerSchema `$ref`'s in an `allOf` in the case that a ref is present and has siblings.
Result:
The following code:
```typescript
import * as t from 'io-ts';
import * as h from '@api-ts/io-ts-http';
/**
* A simple route with type descriptions for references
*
* @operationId api.v1.test
* @tag Test Routes
*/
export const route = h.httpRoute({
path: '/foo',
method: 'GET',
request: h.httpRequest({}),
response: {
200: SimpleRouteResponse
},
});
/**
* Human readable description of the Simple Route Response
* @title Human Readable Simple Route Response
*/
const SimpleRouteResponse = t.type({
/** List of test refs */
test: t.array(TestRef)
});
const …
```
> fix: fix no-$ref-siblings error

- packages/typed-express-router/README.md
Closes DX-1641
This PR updates the README now that `onDecodeError` and `onEncodeError` are no longer used.
Context: https://github.com/BitGo/api-ts/pull/1044#issuecomment-3138799911
> docs: update README.md with information regarding new error formatters
